language: php
php: 7.2
dist: xenial

services:
  - postgresql

before_install:
  - psql -c 'create database timeclock;' -U postgres

install:
  - cd sqitch; sqitch --engine pg -u postgres -d timeclock deploy

script:
  - cd sqitch; sqitch --engine pg -u postgres -d timeclock verify

addons:
  postgresql: "10"
  apt:
    update: true
    packages:
      - postgresql-10
      - postgresql-client-10
      - sqitch
